services:

  frontend:
    hostname: frontend
    build:
      context: ./frontend
      target: 'production-stage'
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  proxy:
    depends_on:
      - frontend
    image: nginx:stable-alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
